server:
  port: 8761
eureka:
  instance:
    hostname: locahost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
